### ISSUE TITLE
Manually implement Debug for Interval?

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#103]
I am wondering whether it would be desirable to *manually* implement `Debug` for `Interval`.  Indeed the debug printing is used when tests fail (including in programs/libraries that use inari).  Having the internal representation printed may be confusing to the user as there is no mention of the fact that [a,b] is stored as (-a, b) in the (public) documentation.  Of course, the question is how much the `Debug` printing should differ from the `Display` printing (if at all).  One may want a *feature* to revert the behavior to the automatic `Debug` for use inside inari tests.  Alternatively, if we leave the `Debug` printing as it is, a word of explanation in the `Interval` documentation would be good IMHO.

What do you think?

**Comment by unageek** [comment]
That sounds like a good idea. How about using the format specifier `g` for `Debug`?

It is an orthogonal topic, but I want all formatting types to produce round-tripping representation.

> One may want a feature to revert the behavior to the automatic Debug for use inside inari tests.

I got confused by the current `Debug` output while debugging the crate itself. Therefore, I think it is also desirable to have a natural output most of the time.

**Comment by unageek** [comment]
Done in #105.
