### ISSUE TITLE
outward-directed rounding

### ISSUE THREAD

**Issue by pcarbonn** [unageek/inari#107]
It's not clear to me whether inari does outward-directed rounding of computations, i.e., that every computed interval is guaranteed to include the hull of the theoretical computation.  You may want to clarify that in the documentation (unless I have missed it).

I see in the source code that the internal representation of [a,b] is [[-a, b]], and that [a,b]+[c,d] is computed as [[(-a)+(- c); b + d]]:  this accomplishes outward-rouding if addition rounds up.  Is that so ?

**Comment by Chris00** [comment]
> It's not clear to me whether inari does outward-directed rounding of computations, i.e., that every computed interval is guaranteed to include the hull of the theoretical computation. 

It does.  It is implicit in the fact that it implements the standard [IEEE Std 1788.1-2017](https://doi.org/10.1109/IEEESTD.2018.8277144).  Actually, IMHO, a library should not call itself an _interval arithmetic_ library if it fails to do that (although some nonetheless do ☹).

**Comment by pcarbonn** [comment]
Thank you for your quick reply.  

As I don't know the details of IEEE standard, I asked chatGPT whether the standard asks for outward-directed rounding, and it answered "no".  Of course, I should never rely on chatGPT, and I'm glad I asked you.
