### ISSUE TITLE
[question] Protected against LLVM reordreing bug?

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#60]
I saw that [LLVM can reorder rounding-mode-sensitive float operations outside rounding mode changes in SSE](https://github.com/rust-lang/rust/issues/72252) so I was wondering whether Inari is affected by this.  While I am at it, I would like to make sure that I understood well the code (my ASM is _very_ limited) and that there is no rounding that can adversely affect the result when stored from extended precision into memory.  (I want to use your library for computer assisted proofs and I'd like to be reassured that it is 100% reliable. 😀)

**Comment by unageek** [comment]
The [`add_ru`](https://github.com/unageek/inari/blob/4f628f5ebd9a32fafcbac661bbf7fd769fcc5949/src/simd/x86_64/avx_fma.rs#L37) function, for example, does the following:

1. Save the current value of the MXCSR register to the stack.
2. Set the value of the MXCSR register to `24448` or `0x5F80`, which tells FP operations to round the result toward +∞, while suppressing any FP exceptions.
3. Perform FP addition.
4. Restore the saved value of the MXCSR register.

The above operations are embedded in a single inline asm, which is immune to optimizations.
