### ISSUE TITLE
Expose directed rounding functions?

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#61]
In a project, I need to implement the function
![image](https://user-images.githubusercontent.com/1255665/146692354-c94ad41e-027a-474b-9701-ab8e877406d9.png)
Clearly I cannot do it naively because the singularity of the logarithm at 0.  To that aim, directed rounding methods (such as `x.add_ru(y)`, `x.mul_rd(y)`,...) would be useful.  Of course I can always make a singleton with each boundary point by I would be making twice as many computations (and half would be thrown away).  What do you think?

**Comment by unageek** [comment]
I'm not sure about how you are going to use `add_ru`, etc., but if you want to experiment with them, you can `git clone` inari locally, and change `inari = "0.x"` to `inari = { path = "/path/to/inari" }` in your project's `Cargo.toml` (please check [Specifying path dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies).) Then, you will be able to expose any functions from inari.
