### ISSUE TITLE
Function `from` ?

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#66]
How about a function `from(x: f64) → Interval`?  Its definition would be:
- `from(NAN) = ∅` 
- `from(+∞) = [f64::MAX, f64::INFINITY]`
-  `from(-∞) = [f64::NEG_INFINITY, f64::MIN]`
- otherwise `from(x) = [x,x]`.

This could be useful for producing constants in generic code.  What do you think?

**Comment by unageek** [comment]
>This could be useful for producing constants in generic code.

Would you give me an example?

**Comment by unageek** [comment]
Do you have any rationale behind these definitions?

- `from(NAN) = ∅` 
- `from(+∞) = [f64::MAX, f64::INFINITY]`
-  `from(-∞) = [f64::NEG_INFINITY, f64::MIN]`

**Comment by Chris00** [comment]
> I don't understand what you mean by this. Could you be more specific?

Suppose I want to write code generic in the type of the interval (in case I need multiprecision intervals in the future).  That code is likely to need numerical constants and it would be good to have a generic way of converting them to intervals.  Example simplified from real code:

```Rust
struct D2<I> { d11: I, // ∂ₓₓ
               d12: I,
               d22: I }

fn mean_integ<I>(f00: &I, f10: &I, f01: &I, f11: &I, d2fxy: &D2<I>,
                 h1: &I, h2: &I) -> I
where I: AbstractInterval<I> {
    let err11 = *h1 * *h2 * bound_of(d2fxy.d11);
    let err12 = *h1 * *h2 * bound_of(d2fxy.d12);
    let err22 = *h1 * *h2 * bound_of(d2fxy.d22);
    let err = (err11 + err12 + err22) / I::from(12.);
    (*f00 + *f10 + *f01 + *f11) / I::from(4.) + err
}
```

**Comment by Chris00** [comment]
> Do you have any rationale behind these definitions?

I was thinking that `from(f(x))` where f: ℝ → [-∞,+∞] should return an enclosure of f(x).  If f(x) is too large and is rounded to +∞, then the appropriate interval is `[f64::MAX, f64::INFINITY]`.  When f(x) is NaN, it means that x ∉ Dom(f), in which case the interval extension should return ∅ (and, so, `from`).

**Comment by unageek** [comment]
>If f(x) is too large and is rounded to +∞, then the appropriate interval is `[f64::MAX, f64::INFINITY]`.

OK, that makes sense. But this definition can confuse users, since the following does not hold when `a == f64::(NEG_)INFINITY`:

`const_interval!(a, a) == Interval::from(a)`

(Note that `const_interval!(a, a)` results in a compilation error.)

In addition, I hesitate to add non-standardized operations at this moment. cf. https://github.com/unageek/inari/pull/67#issuecomment-1008232465
