### ISSUE TITLE
`_mm_set_pd` v.s. `transmute`

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#75]
This is really minor but I am wondering: any reason to [use `transmute`](https://github.com/unageek/inari/blob/main/src/simd/x86_64.rs#L33) instead of the dedicated [`_mm_set_pd`](https://doc.rust-lang.org/core/arch/x86_64/fn._mm_set_pd.html#)?

**Comment by unageek** [comment]
Yeah, that's because they produce the same assembly, and I prefer simpler code.

**Comment by Chris00** [comment]
Thanks for enlightening me.
