### ISSUE TITLE
Implement the two-output division

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#87]
Having `mul_rev_to_pair` as defined in section 10.5.5 of the standard or possibly taking advantage that Rust has enums
```rust
pub fn div2(self, rhs: Interval) → Union2;
pub enum Union2 {
    Single(Interval),
    Union(Interval, Interval),
}
```
would be useful (e.g. for Newton).  What do you think?

**Comment by unageek** [comment]
How about just returning a pair of `Interval`s, i.e., `(Interval, Interval)`?

**Comment by Chris00** [comment]
Returning a pair (as in the standard) is Ok.  However, the caller has to remember which one is empty in case a single interval is returned so “in the abstract” using algebraic data-types is a better design.  That being said, for Newton, one has to check that N(x) ∩ x ≠ ∅ anyway so a function returning a couple of intervals may even be easier to use.  So I'm fine with returning `(Interval, Interval)`.

**Comment by Chris00** [comment]
I think this is complete, so closing.
