### ISSUE TITLE
Interval: Sync and Send

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#98]
Is there any reason `Interval` is not `Sync` and `Send`?  Motivation (not even speaking of multi-threaded code): the use of `Interval` in `static` variables (say with `OnceCell`) requires that it  is `Sync`.

**Comment by unageek** [comment]
Thank you for pointing that out! `(Dec)Interval`s are indeed thread-safe, so they can implement `Sync` and `Send`. Could you please create a PR for this? I will publish a new version after merging it and once #92 is done.

**Comment by unageek** [comment]
Done in #100.
