### ISSUE TITLE
Compiler bug

### ISSUE THREAD

**Issue by Chris00** [unageek/inari#99]
This is likely not the fault of inari but ATM I cannot reproduce it without it.  If you have an idea of the problem, I'm glad to hear your opinion!
```rust
use inari::{Interval as I, const_interval};

fn f(u: I) -> f64 {
    let t = u.inf() == 0.;
    // let t = u.inf() == -0.;
    // println!("{}", t);
    if t { 1. }
    else { println!("{} {}", u.inf(), u.inf() == 0.);
        u.inf() }
}

fn main() {
    println!("{}", f(const_interval!(0., 0.)));
}
``` 

compiled with `--release` prints

```
-0 true
-0
```

If I compile in debug mode or if I uncomment any of the two commented lines above, it works as intended.

**Comment by Chris00** [comment]
I [reported it to Rust](https://github.com/rust-lang/rust/issues/128243) but your insight is still appreciated.

**Comment by Chris00** [comment]
This is being tracked by Rust — I'm closing this, it was mostly for your information.

**Comment by unageek** [comment]
Wow, this appears to be a simple yet serious bug. Thank you for reporting it to the Rust repo.
